//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ketquanghiencuu
    {
        public int manghiencuu { get; set; }
        public Nullable<int> mabaocaokhoahoc { get; set; }
        public string ngaycongbo { get; set; }
        public string mohinh { get; set; }
        public string yeucaukythuat { get; set; }
        public string dattieuchuan { get; set; }
        public string quymosudung { get; set; }
        public string hinhthucchuyengiao { get; set; }
        public string uudiem { get; set; }
        public string cungcap { get; set; }
        public string ungdung0 { get; set; }
        public Nullable<int> gia { get; set; }
    
        public virtual baocaohoahoc baocaohoahoc { get; set; }
    }
}
