//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public string manv { get; set; }
        public string hoten { get; set; }
        public string bidanh { get; set; }
        public string hinhanh { get; set; }
        public Nullable<short> gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string noisinh { get; set; }
        public string cmnd { get; set; }
        public Nullable<System.DateTime> ncapcmnd { get; set; }
        public string noicapcmnd { get; set; }
        public string dantoc { get; set; }
        public string tongiao { get; set; }
        public string quoctich { get; set; }
        public Nullable<short> tthonnhan { get; set; }
        public string quenquan { get; set; }
        public string dc_ttru { get; set; }
        public string noiohnay { get; set; }
        public string dienthoaidd { get; set; }
        public string email { get; set; }
        public Nullable<int> donvi { get; set; }
        public Nullable<int> chucvu { get; set; }
        public Nullable<int> tdhocvan { get; set; }
        public string datotnghiep { get; set; }
        public string tdcaonhat { get; set; }
        public string ngdaotao { get; set; }
        public string cngdaotao { get; set; }
        public string noidaotao { get; set; }
        public string htdaotao { get; set; }
        public Nullable<System.DateTime> mantn { get; set; }
        public string td_nn { get; set; }
        public string td_tinhoc { get; set; }
        public string status { get; set; }
    
        public virtual chucvu chucvu1 { get; set; }
    }
}
