//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhiemvu
    {
        public int manhiemvu { get; set; }
        public Nullable<int> mabckhoahoc { get; set; }
        public string manvdukienchutri { get; set; }
        public Nullable<int> manvchutri { get; set; }
    
        public virtual baocaohoahoc baocaohoahoc { get; set; }
    }
}
