//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tintuc
    {
        public int matt { get; set; }
        public string tieude { get; set; }
        public string tomtat { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> maloaitt { get; set; }
        public string noidung { get; set; }
        public Nullable<int> luotxem { get; set; }
    
        public virtual loaitintuc loaitintuc { get; set; }
    }
}
